name: build_push_ci

on:
  workflow_run:
    workflows: ["code_check_ci"]
    types:
      - completed

permissions:
  contents: read

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract Docker image version
        id: extract_version
        run: make get-image-version

      - name: Build and push image to DockerHub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            georgeogeorge/fastapi-test:${{ env.DOCKER_IMAGE_VERSION }}
            georgeogeorge/fastapi-test:latest
